export * from './add.icon';
export * from './arrow-down.icon';
export * from './arrow-right.icon';
export * from './information.icon';
export * from './clear.icon';
export * from './search.icon';
export * from './insta-pay.icon';
export * from './pesonet.icon';
export * from './arrow-back.icon';
